[package]
name = "wgpu-playaround"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.11"
log = "0.4"
wgpu = "28.0"
pollster = "0.4"
bytemuck = { version = "1.24", features = [ "derive" ] }
